### ISSUE TITLE
Windows 10 Conflict with concrt140.dll

### ISSUE THREAD

**Issue by robertschweizer** [zeromq/pyzmq#1489]
Hello,

The pyzmq versions 21.0.1 and 21.0.2 cause problems loading one of our binary Python libraries. I tracked it down to concrt140.dll.

Importing concrt140.dll before ZMQ works:

```bash
python -c "import ctypes;ctypes.WinDLL('concrt140.dll');import zmq"
```

Importing ZMQ first (e.g. in a Jupyter notebook) makes the concrt140.dll import fail:

```bash
$ python -c "import zmq;import ctypes;ctypes.WinDLL('concrt140.dll')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\kftf964\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found
```

My system information:
```
libzmq-4.3.3
pyzmq-21.0.2
Python-3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
```

My system concrt140.dll, that's imported by ctypes (I checked with `psutil.Process.memory_maps()`)

![image](https://user-images.githubusercontent.com/12115143/105968630-9ca76680-6087-11eb-9dda-be87e35c020e.png)

Thanks a lot for your help!

**Comment by minrk** [comment]
Do you see this also with pyzmq-20.0, which also bundles concrt140.dll?

Can you also test with the wheel from wheels-win_amd64 artifacts [here](https://github.com/zeromq/pyzmq/actions/runs/512233719#artifacts) which change how concrt.dll is bundled?

I'm just about to make a release for pyzmq 22, which I hope fixes this.

I'm really baffled by how much has changed in the DLL loading when I switched over from appveyor to github actions. It really seems to have changed a lot in ways that don't make any sense (e.g. it makes no sense that loading the same concrt twice would be a problem, and there shouldn't be two different files named concrt140.dll, if I understand the promises MS makes about DLL compatibility).

**Comment by robertschweizer** [comment]
Thanks for the quick reply!

We use pyzmq-20.0.0 for now, which works fine. I don't observe any issues with it.

I tried with the artifact wheel that you linked to, that works! Thanks a lot, then this issue is already fixed. Looking forward to the next release!

**Comment by minrk** [comment]
> I tried with the artifact wheel that you linked to, that works! 

That's a huge relief! I'll cut v22 today, then. I still don't understand why, but I'm glad now I don't have to :) Thanks for testing!
