### ISSUE TITLE
dns names can't include underscores

### ISSUE THREAD

**Issue by jacksonloper** [zeromq/pyzmq#801]
This gives an `invalid_argument` error on my system...

    import sys
    import zmq

    context = zmq.Context()
    socket = context.socket(zmq.SUB)

    socket.connect (b"tcp://joo_joo:10050")

...even if `joo_joo` is mapped to localhost in `/etc/hosts`.  Underscores are indeed forbidden for top-level domain names, but they can definitely be found in subdomains and local network configurations.  

The equivalent code in C++ runs with no difficulty, so I think it's somewhere in pyzmq.

**Comment by UsamaMehboob** [comment]
its not only in pyzmq, its in libzmq as well

**Comment by jacksonloper** [comment]
That's really weird; it works fine on jesse.  Are we running the same test?  I'm running the "Ask and ye shall receive" C++ (and I tried C also) code off of http://zguide.zeromq.org/page:all.  The only thing I changed was I swapped out "localhost" for "mystery_town" and put the line

    127.0.0.1	mystery_town

into my `/etc/hosts`.  That doesn't work for you on ubuntu?

I agree that underscores are allowed in domain names.  That's why we should get this fixed.  (But, as I said, at least as of now, there are no underscores in any top-level domains; see https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains)

On an unrelated note, you have a really excellent hat.  I am jealous.

**Comment by minrk** [comment]
pyzmq performs no checks on the URLs, it just passes them directly to libzmq, so there's nothing for pyzmq to do here. Tested and confirmed as fixed by zeromq/libzmq#1746.

**Comment by jacksonloper** [comment]
Awesome, thanks!  (Still don't know why it worked in my C++ code... oh well)

**Comment by UsamaMehboob** [comment]
Hey thanks for compliment. Ahh.. this hat is long gone :( .
did you run the new code? how did it worked for C++. it was not working for me. I used C and changed implied the similar strategy as you have done
